//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sachin_452.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeDetails
    {
        public int BikeId { get; set; }
        public Nullable<int> SellerId { get; set; }
        public string BrandName { get; set; }
        public string BikeModel { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> KilometresDriven { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public string BikeImages { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
