//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sachin_452.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourites
    {
        public int FavouriteId { get; set; }
        public Nullable<int> BikeId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
